(() => {
  "use strict";
  const $ = (s, r=document) => r.querySelector(s);
  const $$ = (s, r=document) => [...r.querySelectorAll(s)];
  const DATA = window.AIDA_DATA || {};
  const STORAGE_KEY = "aida.functional.v3.state";
  const DAY = 86400000;
  const todayKey = (d=new Date()) => d.toISOString().slice(0,10);
  const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
  const escapeHtml = v => String(v ?? "").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
  const normalize = v => String(v ?? "").normalize("NFKC").toLocaleLowerCase();
  const tokenize = v => normalize(v).replace(/[^a-z0-9\s-]/g," ").split(/\s+/).filter(w=>w.length>1 && !STOP.has(w));
  const STOP = new Set("a an the to of and or is are be as for in on at with from this that it you i me my your do does did can may should would have has had into by not also used use one something someone way indicates expresses form before after often more very".split(" "));
  const source = {
    jpG: DATA.japaneseGrammar?.items || [], yueG: DATA.cantoneseGrammar?.items || [],
    jpV: DATA.japaneseVocabulary?.items || [], yueV: DATA.cantoneseVocabulary?.items || []
  };
  const byId = new Map();
  [["jpG",source.jpG],["yueG",source.yueG],["jpV",source.jpV],["yueV",source.yueV]].forEach(([kind,arr])=>arr.forEach(x=>byId.set(`${kind}:${x.id}`,{kind,item:x})));

  const defaultState = () => ({
    version:3, profile:{name:"Learner",dailyGoal:10,jpTarget:"N5"}, xp:0,
    activity:{}, srs:{}, sessions:0, answers:{correct:0,wrong:0}, lastSession:null
  });
  function loadState(){try{const raw=JSON.parse(localStorage.getItem(STORAGE_KEY));return raw&&raw.version===3?{...defaultState(),...raw,profile:{...defaultState().profile,...raw.profile}}:defaultState()}catch{return defaultState()}}
  let state=loadState();
  function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));renderDashboard()}
  function markActivity(points=1){const k=todayKey();state.activity[k]=(state.activity[k]||0)+points}
  function streak(){let n=0,d=new Date();for(;;){const k=todayKey(d);if((state.activity[k]||0)>0){n++;d=new Date(d.getTime()-DAY)}else break}return n}
  function level(){return Math.max(1,Math.floor(state.xp/100)+1)}
  function itemKey(kind,item){return `${kind}:${item.id}`}
  function srsFor(key){return state.srs[key] || {ease:2.5,interval:0,reps:0,due:Date.now(),seen:0,correct:0,wrong:0,mastery:0,last:0}}
  function schedule(kind,item,rating){
    const key=itemKey(kind,item), s={...srsFor(key)}; s.seen++; s.last=Date.now();
    if(rating<=1){s.reps=0;s.interval=0.007;s.ease=Math.max(1.3,s.ease-.2);s.wrong++}
    else if(rating===2){s.reps++;s.interval=s.reps<=1?0.5:Math.max(1,s.interval*1.2);s.ease=Math.max(1.3,s.ease-.08);s.correct++}
    else if(rating===4){s.reps++;s.interval=s.reps===1?1:s.reps===2?3:Math.max(3,s.interval*s.ease);s.correct++;s.ease+=.02}
    else {s.reps++;s.interval=s.reps===1?3:s.reps===2?7:Math.max(7,s.interval*s.ease*1.35);s.correct++;s.ease+=.08}
    s.mastery=clamp(Math.round((s.reps*12)+(s.ease-1.3)*22-Math.min(30,s.wrong*4)),0,100);
    s.due=Date.now()+s.interval*DAY; state.srs[key]=s; state.xp+=rating<=1?2:rating===2?5:rating===4?9:12; markActivity(1); return s;
  }
  function dueEntries(){const now=Date.now();return Object.entries(state.srs).filter(([,s])=>s.due<=now).sort((a,b)=>a[1].due-b[1].due).map(([key,s])=>({key,s,...(byId.get(key)||{})})).filter(x=>x.item)}
  function learnedEntries(){return Object.entries(state.srs).map(([key,s])=>({key,s,...(byId.get(key)||{})})).filter(x=>x.item)}
  function languageMastery(prefix){const arr=Object.entries(state.srs).filter(([k])=>k.startsWith(prefix));if(!arr.length)return 0;return Math.round(arr.reduce((a,[,s])=>a+(s.mastery||0),0)/arr.length)}
  function weekData(){const out=[];for(let i=6;i>=0;i--){const d=new Date(Date.now()-i*DAY);out.push({key:todayKey(d),day:d.toLocaleDateString(undefined,{weekday:"narrow"}),value:state.activity[todayKey(d)]||0})}return out}

  let toastTimer; const toast=$("#toast");
  function showToast(msg){toast.textContent=msg;toast.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove("show"),2400)}
  function showDialog(el){if(el&&!el.open)el.showModal()}
  function closeDialog(el){if(el?.open)el.close()}

  // ---------- semantic pairing ----------
  const tokenCache=new WeakMap();
  function meaningOf(kind,item){return kind==="jpG"||kind==="yueG"?item.meaning:item.meaning}
  function tokensFor(item,kind){if(tokenCache.has(item))return tokenCache.get(item);const t=new Set(tokenize(meaningOf(kind,item)));tokenCache.set(item,t);return t}
  function semanticScore(a,ak,b,bk){const A=tokensFor(a,ak),B=tokensFor(b,bk);if(!A.size||!B.size)return 0;let hit=0;A.forEach(x=>{if(B.has(x))hit++});const union=new Set([...A,...B]).size;let score=hit/union;const ma=normalize(meaningOf(ak,a)), mb=normalize(meaningOf(bk,b));if(ma===mb)score+=1;if(ma.includes(mb)||mb.includes(ma))score+=.25;return score}
  function bestMatch(item,kind,candidates,candidateKind,limit=6000){let best=null,bestScore=-1;const pool=candidateKind==="yueV"?candidates.slice(0,limit):candidates;for(const c of pool){const s=semanticScore(item,kind,c,candidateKind);if(s>bestScore){bestScore=s;best=c}}return {item:best,score:bestScore}}
  function sample(arr,n){const copy=[...arr];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}return copy.slice(0,n)}
  function buildPairs(focus,level,count,preferCommon){
    const pairs=[];let gCount=focus==="grammar"?count:focus==="vocabulary"?0:Math.ceil(count*.45);let vCount=count-gCount;
    let jpG=source.jpG.filter(x=>level==="all"||x.level===level); if(!jpG.length)jpG=source.jpG;
    for(const jp of sample(jpG,gCount)){const m=bestMatch(jp,"jpG",source.yueG,"yueG");pairs.push({type:"grammar",jpKind:"jpG",jp,yueKind:"yueG",yue:m.item,score:m.score})}
    let jpV=source.jpV.filter(x=>level==="all"||x.level===level);if(!jpV.length)jpV=source.jpV;
    const yuePool=preferCommon?source.yueV.slice(0,8000):source.yueV;
    for(const jp of sample(jpV,vCount)){const m=bestMatch(jp,"jpV",yuePool,"yueV",preferCommon?8000:12000);pairs.push({type:"vocabulary",jpKind:"jpV",jp,yueKind:"yueV",yue:m.item,score:m.score})}
    return sample(pairs,pairs.length);
  }
  function displayMain(kind,item){return kind==="jpG"?item.pattern:kind==="yueG"?item.pattern:kind==="jpV"?item.expression:item.word}
  function displayReading(kind,item){return kind==="jpV"?item.reading||"":kind==="yueG"||kind==="yueV"?item.jyutping||"":""}
  function displayMeta(kind,item){if(kind==="jpG")return [item.level,item.course_group].filter(Boolean).join(" · ");if(kind==="yueG")return [item.level,item.category,item.register].filter(Boolean).join(" · ");if(kind==="jpV")return [item.level,item.tags].filter(Boolean).join(" · ");return item.frequency_rank?`Frequency rank #${item.frequency_rank.toLocaleString()}`:"Cantonese vocabulary"}
  function cultureText(pair){if(pair.type==="grammar"){const y=pair.yue;return `<strong>Cultural / usage lens:</strong> ${escapeHtml(y.usage_note||"Compare function rather than translating word-for-word.")} ${y.register?`Register: ${escapeHtml(y.register)}.`:""} ${y.cross_verified?"This Cantonese point is cross-referenced across both bundled grammar sources.":""}`}return `<strong>Vocabulary strategy:</strong> The words are paired by overlap in their English glosses, not assumed to be perfect one-to-one translations. Learn the collocation and examples before treating them as interchangeable.`}

  // ---------- study engine ----------
  let study={pairs:[],index:0,ratings:[],quizAnswered:false};
  const studyDialog=$("#studyStudio");
  function openStudy(){showDialog(studyDialog);$("#studySetup").classList.remove("hidden");$("#studySession").classList.add("hidden");$("#studyComplete").classList.add("hidden");$("#studySessionProgress").textContent=`${dueEntries().length} reviews due`}
  function generateSession(){const focus=$("#studyFocus").value,level=$("#studyLevel").value,count=Number($("#studyLength").value),common=$("#preferCommonCantonese").checked;$("#generateSession").textContent="Pairing source data…";setTimeout(()=>{study={pairs:buildPairs(focus,level,count,common),index:0,ratings:[],quizAnswered:false};$("#studySetup").classList.add("hidden");$("#studySession").classList.remove("hidden");$("#generateSession").textContent="Generate session →";renderStudyPair()},30)}
  function renderStudyPair(){const p=study.pairs[study.index];if(!p)return finishStudy();const percent=(study.index/study.pairs.length)*100;$("#sessionProgressBar").style.width=`${percent}%`;$("#studySessionProgress").textContent=`${study.index+1} / ${study.pairs.length}`;$("#studyItemType").textContent=`${p.type.toUpperCase()} PAIR`;$("#studyPairScore").textContent=p.score>.35?"Strong meaning overlap":p.score>.12?"Related meaning":"Loose semantic bridge";$("#studyJpMain").textContent=displayMain(p.jpKind,p.jp);$("#studyJpReading").textContent=displayReading(p.jpKind,p.jp);$("#studyJpMeaning").textContent=meaningOf(p.jpKind,p.jp);$("#studyJpMeta").textContent=displayMeta(p.jpKind,p.jp);$("#studyYueMain").textContent=displayMain(p.yueKind,p.yue);$("#studyYueReading").textContent=displayReading(p.yueKind,p.yue);$("#studyYueMeaning").textContent=meaningOf(p.yueKind,p.yue);$("#studyYueMeta").textContent=displayMeta(p.yueKind,p.yue);$("#studyCultureNote").innerHTML=cultureText(p);renderQuiz(p);}
  function renderQuiz(p){study.quizAnswered=false;const correct=meaningOf(Math.random()<.5?p.jpKind:p.yueKind,Math.random()<.5?p.jp:p.yue);const all=p.type==="grammar"?[...source.jpG,...source.yueG]:[...source.jpV.slice(0,3000),...source.yueV.slice(0,5000)];const distract=sample(all.filter(x=>x.meaning&&normalize(x.meaning)!==normalize(correct)),3).map(x=>x.meaning);const options=sample([correct,...distract],4);const prompt=Math.random()<.5?displayMain(p.jpKind,p.jp):displayMain(p.yueKind,p.yue);$("#quizArea").classList.remove("hidden");$("#quizArea").innerHTML=`<h4>Quick check: what best matches <span class="teal">${escapeHtml(prompt)}</span>?</h4><div class="quiz-options">${options.map(o=>`<button class="quiz-option" data-answer="${escapeHtml(o)}">${escapeHtml(o)}</button>`).join("")}</div>`;$$('#quizArea .quiz-option').forEach(b=>b.addEventListener('click',()=>{if(study.quizAnswered)return;study.quizAnswered=true;const ok=b.dataset.answer===correct;b.classList.add(ok?'correct':'wrong');if(!ok){$$('#quizArea .quiz-option').find(x=>x.dataset.answer===correct)?.classList.add('correct');state.answers.wrong++}else state.answers.correct++;saveState()}))}
  function rateCurrent(rating){const p=study.pairs[study.index];schedule(p.jpKind,p.jp,rating);schedule(p.yueKind,p.yue,rating);study.ratings.push(rating);study.index++;if(study.index>=study.pairs.length)finishStudy();else renderStudyPair()}
  function finishStudy(){state.sessions++;state.lastSession={date:Date.now(),count:study.pairs.length};saveState();$("#studySession").classList.add("hidden");$("#studyComplete").classList.remove("hidden");const xp=study.ratings.reduce((a,r)=>a+(r<=1?4:r===2?10:r===4?18:24),0);$("#completeXp").textContent=xp;$("#completeReviewed").textContent=study.pairs.length;$("#completeDue").textContent=dueEntries().length;$("#studyCompleteSummary").textContent=`You studied ${study.pairs.length} Japanese–Cantonese meaning bridges and scheduled ${study.pairs.length*2} source items for spaced review.`}
  function speak(text,lang){if(!('speechSynthesis' in window)){showToast('Speech synthesis is not available in this browser.');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=lang;const voices=speechSynthesis.getVoices();const preferred=voices.find(v=>lang==='ja-JP'?v.lang.toLowerCase().startsWith('ja'):v.lang.toLowerCase().includes('yue')||v.lang.toLowerCase()==='zh-hk');if(preferred)u.voice=preferred;u.rate=.85;speechSynthesis.speak(u)}

  // ---------- review engine ----------
  const reviewDialog=$("#reviewStudio"); let reviewQueue=[],reviewIndex=0,reviewRevealed=false;
  function openReview(){showDialog(reviewDialog);reviewQueue=dueEntries();if(!reviewQueue.length){const learned=learnedEntries().sort((a,b)=>(a.s.mastery||0)-(b.s.mastery||0));if(learned.length)reviewQueue=[learned[0]]}reviewIndex=0;renderReviewCard()}
  function renderReviewCard(){if(!reviewQueue.length){$("#reviewEmpty").classList.remove("hidden");$("#reviewSession").classList.add("hidden");return}if(reviewIndex>=reviewQueue.length){closeDialog(reviewDialog);showToast('Review complete.');saveState();return}$("#reviewEmpty").classList.add("hidden");$("#reviewSession").classList.remove("hidden");reviewRevealed=false;const e=reviewQueue[reviewIndex],kind=e.kind,item=e.item;$("#reviewSessionCount").textContent=`${reviewIndex+1} / ${reviewQueue.length}`;$("#reviewSessionDue").textContent=`Mastery ${e.s.mastery||0}%`;$("#reviewSideLabel").textContent=kind.startsWith('jp')?'JAPANESE RECALL':'CANTONESE RECALL';$("#reviewPrompt").textContent=displayMain(kind,item);$("#reviewPromptSub").textContent=displayReading(kind,item)||'Recall the meaning and usage before revealing.';$("#reviewReveal").classList.add('hidden');$("#reviewReveal").innerHTML=`<strong>${escapeHtml(meaningOf(kind,item))}</strong><small>${escapeHtml(displayMeta(kind,item))}</small>`;$("#reviewControls").innerHTML=`<button class="btn primary" id="revealReview">Reveal answer</button>`;$("#revealReview").addEventListener('click',revealReview)}
  function revealReview(){reviewRevealed=true;$("#reviewReveal").classList.remove('hidden');$("#reviewControls").innerHTML=`<div class="review-rating-row"><button class="rating-btn again" data-review-rating="1">Again</button><button class="rating-btn hard" data-review-rating="2">Hard</button><button class="rating-btn good" data-review-rating="4">Good</button><button class="rating-btn easy" data-review-rating="5">Easy</button></div>`;$$('[data-review-rating]').forEach(b=>b.addEventListener('click',()=>{const e=reviewQueue[reviewIndex];schedule(e.kind,e.item,Number(b.dataset.reviewRating));reviewIndex++;renderReviewCard()}))}

  // ---------- usage lab ----------
  let labMode='ja';
  function fixedCjkChunks(pattern){return String(pattern||'').replace(/[A-Z]+|PLACE|NOUN|VERB|ADJ|V|A|B|X|Y/g,' ').split(/[\s〜~＋+\/（）()…\.・]+/).map(x=>x.trim()).filter(x=>x.length>=1)}
  function matchGrammar(sentence,mode){const arr=mode==='yue'?source.yueG:source.jpG;const hits=[];for(const item of arr){const chunks=fixedCjkChunks(item.pattern).filter(c=>c.length>=1);const score=chunks.filter(c=>sentence.includes(c)).length;if(score&&chunks.some(c=>c.length>=2||sentence===c))hits.push({item,score:score/chunks.length})}return hits.sort((a,b)=>b.score-a.score).slice(0,8)}
  function matchVocab(sentence,mode){const arr=mode==='yue'?source.yueV:source.jpV;const hits=[];for(const item of arr){const word=mode==='yue'?item.word:item.expression;if(word&&word.length>=1&&sentence.includes(word))hits.push(item)}if(mode==='yue')hits.sort((a,b)=>(a.frequency_rank||999999)-(b.frequency_rank||999999));else hits.sort((a,b)=>(b.expression?.length||0)-(a.expression?.length||0));return hits.slice(0,12)}
  function registerInference(sentence,mode,grammarHits){if(mode==='ja'){if(/です|ます|ください|ません|でしょう|いただ/.test(sentence))return {label:'Polite / formal markers detected',score:90};if(/[だよねなぞぜ]$/.test(sentence)||/[！？!?]$/.test(sentence))return {label:'Likely casual or neutral conversational style',score:72};return {label:'Register is ambiguous without more context',score:55}}const regs=grammarHits.map(h=>h.item.register).filter(Boolean);if(regs.length)return {label:`Matched grammar register: ${[...new Set(regs)].join(', ')}`,score:85};if(/[呀啦喇喎啫㗎嘛呢]$/.test(sentence))return {label:'Conversational sentence-final particle detected',score:82};return {label:'Register is ambiguous without relationship context',score:55}}
  function equivalentSuggestions(grammarHits,vocabHits,mode){const out=[];const targetG=mode==='ja'?source.yueG:source.jpG,targetV=mode==='ja'?source.yueV.slice(0,8000):source.jpV;for(const h of grammarHits.slice(0,3)){const m=bestMatch(h.item,mode==='ja'?'jpG':'yueG',targetG,mode==='ja'?'yueG':'jpG');if(m.item)out.push({type:'grammar',item:m.item,kind:mode==='ja'?'yueG':'jpG',score:m.score})}for(const v of vocabHits.slice(0,2)){const m=bestMatch(v,mode==='ja'?'jpV':'yueV',targetV,mode==='ja'?'yueV':'jpV',8000);if(m.item)out.push({type:'vocab',item:m.item,kind:mode==='ja'?'yueV':'jpV',score:m.score})}return out}
  function analyzeUsage(){const sentence=$("#usageInput").value.trim();if(!sentence){showToast('Type a sentence first.');return}const mode=labMode==='compare'?( /[ぁ-んァ-ン]/.test(sentence)?'ja':'yue'):labMode;const g=matchGrammar(sentence,mode),v=matchVocab(sentence,mode),reg=registerInference(sentence,mode,g);const structure=clamp(40+g.length*12+Math.min(20,v.length*3),40,100),meaning=clamp(35+(g.length?25:0)+Math.min(35,v.length*6),35,95);const eq=equivalentSuggestions(g,v,mode);$$('.verify-row').forEach((row,i)=>{const val=[structure,meaning,reg.score][i];row.style.borderColor=val>=75?'rgba(83,224,212,.38)':val>=55?'rgba(244,189,93,.35)':'rgba(255,110,110,.35)';$('.verify-check',row).textContent=`${val}%`});const grammarHtml=g.length?g.map(({item})=>`<div class="analysis-match"><b>${escapeHtml(item.pattern)}</b> — ${escapeHtml(item.meaning)} ${item.cross_verified?'<span class="teal">· cross-verified</span>':''} ${item.source_url?`· <a target="_blank" rel="noopener" href="${escapeHtml(item.source_url)}">source</a>`:''}</div>`).join(''):'<div class="analysis-match">No exact grammar pattern from the local source index was confidently detected.</div>';const vocabHtml=v.length?v.slice(0,6).map(item=>`<div class="analysis-match"><b>${escapeHtml(mode==='ja'?item.expression:item.word)}</b>${displayReading(mode==='ja'?'jpV':'yueV',item)?` · ${escapeHtml(displayReading(mode==='ja'?'jpV':'yueV',item))}`:''} — ${escapeHtml(item.meaning)}</div>`).join(''):'<div class="analysis-match">No vocabulary entries were matched exactly.</div>';const eqHtml=eq.length?eq.slice(0,5).map(x=>`<div class="analysis-match"><b>${escapeHtml(displayMain(x.kind,x.item))}</b>${displayReading(x.kind,x.item)?` · ${escapeHtml(displayReading(x.kind,x.item))}`:''} — ${escapeHtml(meaningOf(x.kind,x.item))}</div>`).join(''):'<div class="analysis-match">No strong cross-language equivalent was found from the local pools.</div>';$("#labAnalysis").innerHTML=`<div class="analysis-summary"><div class="analysis-score"><strong>${structure}%</strong><span>structure evidence</span></div><div class="analysis-score"><strong>${meaning}%</strong><span>meaning evidence</span></div><div class="analysis-score"><strong>${reg.score}%</strong><span>register confidence</span></div></div><div class="analysis-section"><h4>Detected grammar</h4>${grammarHtml}</div><div class="analysis-section"><h4>Detected vocabulary</h4>${vocabHtml}</div><div class="analysis-section"><h4>Register</h4><div class="analysis-match ${reg.score<70?'analysis-warning':''}">${escapeHtml(reg.label)}. A relationship and situation are still required for a definitive social-fit judgment.</div></div><div class="analysis-section"><h4>${mode==='ja'?'Cantonese':'Japanese'} meaning bridges</h4>${eqHtml}</div>`}

  // ---------- library ----------
  const library=$("#dataLibrary"), librarySearch=$("#librarySearch"), libraryResults=$("#libraryResults"), libraryDatasetLabel=$("#libraryDatasetLabel"), libraryResultCount=$("#libraryResultCount");let currentDataset='japaneseGrammar',searchTimer;
  const datasetConfig={japaneseGrammar:{label:'Japanese grammar',items:source.jpG,type:'jpG'},cantoneseGrammar:{label:'Cantonese grammar',items:source.yueG,type:'yueG'},japaneseVocabulary:{label:'Japanese vocabulary',items:source.jpV,type:'jpV'},cantoneseVocabulary:{label:'Cantonese vocabulary',items:source.yueV,type:'yueV'}};
  function searchText(kind,item){return kind==='jpG'?[item.pattern,item.meaning,item.level,item.course_group].join(' '):kind==='yueG'?[item.pattern,item.jyutping,item.meaning,item.category,item.usage_note,item.register].join(' '):kind==='jpV'?[item.expression,item.reading,item.meaning,item.tags,item.level].join(' '):[item.word,item.jyutping,item.meaning,item.note,...(item.examples||[]).flatMap(e=>[e.sentence,e.meaning,e.jyutping])].join(' ')}
  function renderLibraryItem(kind,item){const main=displayMain(kind,item),read=displayReading(kind,item),meaning=meaningOf(kind,item),meta=displayMeta(kind,item);let sourceHtml='';if(kind==='jpG'&&item.source_url)sourceHtml=`<a href="${escapeHtml(item.source_url)}" target="_blank" rel="noopener">Bunpro source</a>`;if(kind==='yueG'&&item.sources?.length)sourceHtml=item.sources.map(s=>`<a href="${escapeHtml(s.url)}" target="_blank" rel="noopener">${escapeHtml(s.name)}</a>`).join(' · ');return `<article class="library-item"><div class="library-term"><strong>${escapeHtml(main)}</strong><small>${escapeHtml(read)}</small></div><div class="library-description"><p>${escapeHtml(meaning)}</p><small>${escapeHtml(meta)}</small><div class="library-source-links">${sourceHtml}</div></div><div class="library-badges">${kind==='yueG'&&item.cross_verified?'<span class="library-badge verified">Cross-verified</span>':''}${kind==='yueV'&&item.frequency_rank?`<span class="library-badge verified">Rank #${item.frequency_rank.toLocaleString()}</span>`:''}${kind==='jpG'?'<span class="library-badge">Source-indexed</span>':''}</div></article>`}
  function renderLibrary(){const c=datasetConfig[currentDataset],q=normalize(librarySearch.value.trim()),terms=q.split(/\s+/).filter(Boolean);const matches=!q?c.items:c.items.filter(i=>{const h=normalize(searchText(c.type,i));return terms.every(t=>h.includes(t))});const vis=matches.slice(0,80);libraryDatasetLabel.textContent=c.label;libraryResultCount.textContent=`${matches.length.toLocaleString()} matches · showing ${vis.length}`;libraryResults.innerHTML=vis.length?vis.map(i=>renderLibraryItem(c.type,i)).join(''):'<div class="library-empty">No matches found.</div>'}
  function openLibrary(dataset){if(dataset)currentDataset=dataset;$$('[data-dataset]').forEach(b=>b.classList.toggle('active',b.dataset.dataset===currentDataset));librarySearch.value='';renderLibrary();showDialog(library)}

  // ---------- profile/progress/dashboard ----------
  function renderDashboard(){const jp=languageMastery('jp'),yue=languageMastery('yue'),overall=Math.round((jp+yue)/2),due=dueEntries(),st=streak(),lvl=level();$("#streak").textContent=st;$("#profileNameTop").textContent=state.profile.name;$("#profileLevelTop").textContent=`Level ${lvl}`;$("#avatarTop").textContent=(state.profile.name.trim()[0]||'間').toUpperCase();$("#jpProgressRing").style.setProperty('--value',jp);$("#jpProgressValue").textContent=`${jp}%`;$("#yueProgressRing").style.setProperty('--value',yue);$("#yueProgressValue").textContent=`${yue}%`;$("#overallProgressValue").textContent=`${overall}%`;const w=weekData(),sum=w.reduce((a,x)=>a+x.value,0);$("#weeklyProgressText").textContent=sum?`${sum} reviews this week`:'Start your first lesson';const max=Math.max(1,...w.map(x=>x.value));$("#weekChart").innerHTML=w.map(x=>`<i style="--h:${Math.max(8,Math.round(x.value/max*100))}%" title="${x.key}: ${x.value}"></i>`).join('');$("#reviewDueCount").textContent=`${due.length} ›`;const list=$("#reviewList");if(!due.length)list.innerHTML='<button class="review-item empty-review">Nothing due yet — study a session to seed SRS.</button>';else list.innerHTML=due.slice(0,3).map(e=>`<button class="review-item" data-action="review"><span class="lang-dot ${e.kind.startsWith('jp')?'teal-dot':'gold-dot'}">${e.kind.startsWith('jp')?'日':'粵'}</span><span><strong>${escapeHtml(displayMain(e.kind,e.item))}</strong><small>Mastery ${e.s.mastery||0}%</small></span><em>Due</em></button>`).join('');$$('#reviewList [data-action="review"]').forEach(b=>b.addEventListener('click',openReview));$("#countJpGrammar").textContent=source.jpG.length.toLocaleString();$("#countYueGrammar").textContent=source.yueG.length.toLocaleString();$("#countJpVocab").textContent=source.jpV.length.toLocaleString();$("#countYueVocab").textContent=source.yueV.length.toLocaleString();$("#grammarPoolCount").textContent=`${(source.jpG.length+source.yueG.length).toLocaleString()} grammar points`;$("#vocabPoolCount").textContent=`${(source.jpV.length+source.yueV.length).toLocaleString()} vocabulary entries`;}
  function openProfile(){const d=$("#profileDialog");$("#profileNameInput").value=state.profile.name;$("#dailyGoalInput").value=String(state.profile.dailyGoal);$("#jpTargetInput").value=state.profile.jpTarget;const learned=learnedEntries();$("#profileStats").innerHTML=`<div class="profile-stat"><strong>${state.xp}</strong><span>total XP</span></div><div class="profile-stat"><strong>${learned.length}</strong><span>source items learned</span></div><div class="profile-stat"><strong>${streak()}</strong><span>day streak</span></div>`;showDialog(d)}
  function saveProfile(){state.profile={name:$("#profileNameInput").value.trim()||'Learner',dailyGoal:Number($("#dailyGoalInput").value),jpTarget:$("#jpTargetInput").value};saveState();closeDialog($("#profileDialog"));showToast('Profile saved locally.')}
  function openProgress(){const learned=learnedEntries(),due=dueEntries();const buckets=[['Japanese grammar','jpG'],['Cantonese grammar','yueG'],['Japanese vocabulary','jpV'],['Cantonese vocabulary','yueV']];const totalAnswers=state.answers.correct+state.answers.wrong,accuracy=totalAnswers?Math.round(state.answers.correct/totalAnswers*100):0;$("#progressDashboard").innerHTML=`<div class="progress-kpis"><div class="progress-kpi"><strong>${state.xp}</strong><span>Total XP</span></div><div class="progress-kpi"><strong>${learned.length}</strong><span>Learned items</span></div><div class="progress-kpi"><strong>${due.length}</strong><span>Reviews due</span></div><div class="progress-kpi"><strong>${accuracy}%</strong><span>Quiz accuracy</span></div></div><div class="mastery-table">${buckets.map(([label,prefix])=>{const v=languageMastery(prefix);const count=Object.keys(state.srs).filter(k=>k.startsWith(prefix+':')).length;return `<div class="mastery-row"><span>${label} · ${count}</span><div class="mastery-bar"><i style="width:${v}%"></i></div><strong>${v}%</strong></div>`}).join('')}</div>`;showDialog($("#progressDialog"))}
  function exportProgress(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`aida-progress-${todayKey()}.json`;a.click();URL.revokeObjectURL(url)}
  function importProgress(file){const r=new FileReader();r.onload=()=>{try{const incoming=JSON.parse(r.result);if(!incoming||typeof incoming!=='object')throw new Error();state={...defaultState(),...incoming,version:3,profile:{...defaultState().profile,...incoming.profile}};saveState();closeDialog($("#profileDialog"));showToast('Progress imported.')}catch{showToast('Could not import that progress file.')}};r.readAsText(file)}

  // ---------- wire UI ----------
  $$('[data-action]').forEach(btn=>btn.addEventListener('click',()=>{const a=btn.dataset.action;if(a==='open-study'||a==='continue'||a==='start-lesson'||a==='new-session')openStudy();else if(a==='close-study')closeDialog(studyDialog);else if(a==='review')openReview();else if(a==='close-review')closeDialog(reviewDialog);else if(a==='profile')openProfile();else if(a==='close-profile')closeDialog($("#profileDialog"));else if(a==='progress')openProgress();else if(a==='close-progress')closeDialog($("#progressDialog"));else if(a==='data-library')openLibrary();else if(a==='close-library')closeDialog(library);else if(a==='close-modal')closeDialog($("#modal"));else if(a==='how'){const m=$("#modal"),body=$("#modalBody");body.innerHTML='<div class="modal-kicker">HOW AIDA WORKS</div><h2 class="modal-title">Source pools → semantic bridges → active recall</h2><p class="modal-copy">Sessions are generated from the bundled grammar and vocabulary files. English gloss overlap creates a bridge between Japanese and Cantonese, your confidence ratings schedule both items with spaced repetition, and all progress is stored locally in your browser.</p>';showDialog(m)}}));
  $("#generateSession").addEventListener('click',generateSession);$$('[data-rating]').forEach(b=>b.addEventListener('click',()=>rateCurrent(Number(b.dataset.rating))));$("#speakJapanese").addEventListener('click',()=>{const p=study.pairs[study.index];if(p)speak(displayMain(p.jpKind,p.jp),'ja-JP')});$("#speakCantonese").addEventListener('click',()=>{const p=study.pairs[study.index];if(p)speak(displayMain(p.yueKind,p.yue),'yue-HK')});
  $$('.lab-tabs button').forEach(b=>b.addEventListener('click',()=>{$$('.lab-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');labMode=b.dataset.lab;$("#usageInput").placeholder=labMode==='ja'?'日本語の文を入力…':labMode==='yue'?'輸入廣東話句子…':'Enter Japanese or Cantonese to find meaning bridges…'}));$("#usageInput").addEventListener('input',e=>$("#charCount").textContent=`${e.target.value.length}/200`);$("#sendUsage").addEventListener('click',analyzeUsage);const examples={'丁寧にお願いする':'ここに座ってもいいですか？','朋友に誘う':'聽日一齊去食飯呀？','相手を気遣う':'無理しなくてもいいですよ。'};$$('[data-example]').forEach(b=>b.addEventListener('click',()=>{$("#usageInput").value=examples[b.dataset.example];$("#usageInput").dispatchEvent(new Event('input'));analyzeUsage()}));
  $$('[data-curriculum]').forEach(card=>card.addEventListener('click',()=>openLibrary(card.dataset.curriculum==='Grammar'?'japaneseGrammar':card.dataset.curriculum==='Vocabulary'?'japaneseVocabulary':'cantoneseGrammar')));$$('[data-dataset]').forEach(b=>b.addEventListener('click',()=>{currentDataset=b.dataset.dataset;$$('[data-dataset]').forEach(x=>x.classList.toggle('active',x===b));librarySearch.value='';renderLibrary()}));librarySearch.addEventListener('input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(renderLibrary,120)});$("#randomLibraryItem").addEventListener('click',()=>{const c=datasetConfig[currentDataset],item=c.items[Math.floor(Math.random()*c.items.length)];librarySearch.value=displayMain(c.type,item);renderLibrary()});
  $("#saveProfile").addEventListener('click',saveProfile);$("#exportProgress").addEventListener('click',exportProgress);$("#importProgress").addEventListener('change',e=>e.target.files?.[0]&&importProgress(e.target.files[0]));$(".streak-chip").addEventListener('click',()=>showToast(`${streak()}-day streak · today's activity: ${state.activity[todayKey()]||0}/${state.profile.dailyGoal} items`));
  $$('[data-scroll]').forEach(btn=>btn.addEventListener('click',()=>{const id=btn.dataset.scroll;(id==='top'?document.body:document.getElementById(id))?.scrollIntoView({behavior:'smooth',block:'start'})}));
  [$("#modal"),library,studyDialog,reviewDialog,$("#profileDialog"),$("#progressDialog")].forEach(d=>d?.addEventListener('click',e=>{if(e.target===d)d.close()}));
  renderDashboard();
})();